package ui;

// Import SQL classes for database operations
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

// Import Swing classes for dialogs
import javax.swing.JOptionPane;

// Import database connection class
import db.DBConnection;

// Import text component class for styling fields
import javax.swing.text.JTextComponent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Alshuruq Company
 */
public class B__Signup extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(B__Signup.class.getName());

    /**
     * Creates new form signup
     */
    public B__Signup() {
        initComponents();
        // Center the window on the screen
        setLocationRelativeTo(null);

        // Apply custom style to text fields
        styleField(txt_username);
        styleField(txt_address);
        styleField(txt_phone);
        styleField(txt_password);
        styleField(txt_confirm_pass);

        // Style "show password" checkbox
        chk_show_pass.setOpaque(false); // Make checkbox background transparent
        chk_show_pass.setForeground(new java.awt.Color(102, 51, 0)); // Set text color to brown
        chk_show_pass.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12)); // Set font style


        // Apply custom style to buttons
        styleButton(btn_signup);
        styleButton(jButton3);

        // Move focus to address field when Enter is pressed in username field
        txt_username.addActionListener(e -> txt_address.requestFocus());

        // Move focus to password field when Enter is pressed in address field
        txt_address.addActionListener(e -> txt_password.requestFocus());

        // Move focus to confirm password field when Enter is pressed in password field
        txt_password.addActionListener(e -> txt_confirm_pass.requestFocus());

        // Move focus to phone field when Enter is pressed in confirm password field
        txt_confirm_pass.addActionListener(e -> txt_phone.requestFocus());

        // Click the Sign Up button when Enter is pressed in phone field
        txt_phone.addActionListener(e -> btn_signup.doClick());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_signup = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chk_show_pass = new javax.swing.JCheckBox();
        txt_password = new javax.swing.JPasswordField();
        txt_confirm_pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_signup.setBackground(new java.awt.Color(165, 117, 68));
        btn_signup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_signup.setText("SIGN UP");
        btn_signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        jPanel1.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 650, 260, 40));
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 260, 40));
        jPanel1.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 260, 40));

        txt_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneActionPerformed(evt);
            }
        });
        txt_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phoneKeyTyped(evt);
            }
        });
        jPanel1.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 260, 40));

        jButton3.setBackground(new java.awt.Color(243, 207, 170));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("←");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 60, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Username:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Address:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Confirm Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Phone Number:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 140, -1));

        chk_show_pass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_show_pass.setText("show password");
        chk_show_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_show_passActionPerformed(evt);
            }
        });
        jPanel1.add(chk_show_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, -1, -1));
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 260, 40));

        txt_confirm_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_confirm_passActionPerformed(evt);
            }
        });
        jPanel1.add(txt_confirm_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 260, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basicc.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1145, 863));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private boolean show = false;
    private void chk_show_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_show_passActionPerformed
if (!show) {
            // إظهار النص في الخانتين
            txt_password.setEchoChar((char) 0);
            txt_confirm_pass.setEchoChar((char) 0);
            show = true;
        } else {
            // إخفاء النص في الخانتين
            txt_password.setEchoChar('*');
            txt_confirm_pass.setEchoChar('*');
            show = false;
        }    }//GEN-LAST:event_chk_show_passActionPerformed

    private void txt_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // Read user input from text fields
        String name = txt_username.getText().trim();
        String address = txt_address.getText().trim();
        String phone = txt_phone.getText().trim();
        String pass = new String(txt_password.getPassword()).trim();
        String confirm = new String(txt_confirm_pass.getPassword()).trim();

        // Check if any field is empty
        if (name.isEmpty() || address.isEmpty() || phone.isEmpty() || pass.isEmpty() || confirm.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields ");
            return; // Stop execution
        }

        // Check if password and confirm password match
        if (!pass.equals(confirm)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match ️");
            return; // Stop execution
        }

        try {
            // Get database connection
            Connection con = DBConnection.getConnection();

            // Check if the phone number already exists
            String checkSql = "SELECT * FROM Customers WHERE PHONE_NUMBER = ?";
            PreparedStatement checkPst = con.prepareStatement(checkSql);
            checkPst.setString(1, phone);
            ResultSet rs = checkPst.executeQuery();

            // If phone number exists, show message
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Phone number already exists! Please Login");
            } else {
                // Insert new customer data into the database
String insertSql = "INSERT INTO Customers (USER_NAME, PHONE_NUMBER, PASSWORD, CUSTOMER_ADDRESS, ROLE) VALUES (?, ?, ?, ?, 'User')";                PreparedStatement pst = con.prepareStatement(insertSql);

                // Set customer values
                pst.setString(1, name);
                pst.setString(2, phone);
                pst.setString(3, pass);
                pst.setString(4, address);

                // Execute insert
                pst.executeUpdate();

                // Show success message
                JOptionPane.showMessageDialog(this, "Account Created Successfully! Please Login");

                // Clear all input fields
                txt_username.setText("");
                txt_address.setText("");
                txt_phone.setText("");
                txt_password.setText("");
                txt_confirm_pass.setText("");

                // Close signup window and open login window
                this.dispose();
                new B__Login().setVisible(true);
            }

            // Close database connection
            con.close();

        } catch (Exception e) {
            // Show error message if something goes wrong
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_signupActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();

        new A__Welcome().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyTyped
        // Get the character that was typed by the user
        char c = evt.getKeyChar();

        // If the character is not a digit (like letters or symbols)
        if (!Character.isDigit(c)) {
            // Prevent the character from being added to the field
            evt.consume(); 
        }

        // If the phone number field already has 11 characters or more
        if (txt_phone.getText().length() >= 11) {
            // Prevent additional characters from being added
            evt.consume();
        }     
    }//GEN-LAST:event_txt_phoneKeyTyped

    private void txt_confirm_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_confirm_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_confirm_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new B__Signup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signup;
    private javax.swing.JCheckBox chk_show_pass;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_address;
    private javax.swing.JPasswordField txt_confirm_pass;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    // ديه علشان الشكل بس يعني مش مهمة اوي اننا نعرف كل حاجة في الكود بتاعها
    
    // Method to apply custom styling to text fields   
    private void styleField(JTextComponent field) {
        // Define brown color for borders and accents
        java.awt.Color brownColor = new java.awt.Color(102, 51, 0);

        // Define tan highlight color for active states
        java.awt.Color tanHighlight = new java.awt.Color(255, 224, 178);

        // Make the field transparent
        field.setOpaque(false);
        // Set background to fully transparent black
        field.setBackground(new java.awt.Color(0, 0, 0, 0));

        // Set font to bold size 15
        field.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 15));
        // Set text color to tan highlight
        field.setForeground(tanHighlight);

        // If the component is a text field, center the text horizontally
        if (field instanceof javax.swing.JTextField) {
            ((javax.swing.JTextField) field).setHorizontalAlignment(javax.swing.JTextField.CENTER);
        }

        // Apply custom rounded border with specified radius and color
        field.setBorder(new RoundedBorder(30, brownColor));

        // Add focus listener to change border color when field gains/loses focus
        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                // Change border to tan highlight when focused
                field.setBorder(new RoundedBorder(30, tanHighlight));
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                // Change border back to brown when focus is lost
                field.setBorder(new RoundedBorder(30, brownColor));
            }
        });
    }

// Method to apply custom styling to buttons
    private void styleButton(javax.swing.JButton btn) {
        // Set font to bold size 14
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        // Set text color to white
        btn.setForeground(java.awt.Color.WHITE);
        // Set background color to brown
        btn.setBackground(new java.awt.Color(102, 51, 0));
        // Don't paint the border
        btn.setBorderPainted(false);
        // Don't show focus border
        btn.setFocusPainted(false);
        // Change cursor to hand when hovering over button
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Add mouse listener to change background color on hover
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Lighter brown color when mouse enters
                btn.setBackground(new java.awt.Color(165, 117, 68));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Original brown color when mouse exits
                btn.setBackground(new java.awt.Color(102, 51, 0));
            }
        });
    }

    // Custom border class that creates rounded corners
    class RoundedBorder implements javax.swing.border.Border {

        // Radius of the rounded corners
        private int radius;
        // Color of the border
        private java.awt.Color color;

        // Constructor to set radius and color
        RoundedBorder(int radius, java.awt.Color color) {
            this.radius = radius;
            this.color = color;
        }

        // Method to define the border margins around the component
        public java.awt.Insets getBorderInsets(java.awt.Component c) {
            // Return insets with top/bottom of 5px and sides of half the radius
            return new java.awt.Insets(5, radius / 2, 5, radius / 2);
        }

        // Method to specify if border should be opaque
        public boolean isBorderOpaque() {
            return true;
        }

        // Method to draw the border on the component
        public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
            // Cast graphics object to Graphics2D for advanced drawing
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
            // Enable anti-aliasing for smooth edges
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
            // Set the border color
            g2.setColor(color);
            // Set stroke thickness to 2 pixels
            g2.setStroke(new java.awt.BasicStroke(2));
            // Draw the rounded rectangle border
            g2.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
        }
    }
}
