package ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class C__About_us extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(C__About_us.class.getName());

    /**
     * Creates new form aboutus
     */
    public C__About_us() {
        initComponents();
         setLocationRelativeTo(null);
          styleButton(jButton3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("About Us");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 120, 30));

        jButton3.setBackground(new java.awt.Color(243, 207, 170));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("←");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 60, 30));

        jScrollPane1.setBackground(new java.awt.Color(165, 117, 68));
        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(165, 117, 68));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(" \nAt Zar Café, we believe that great moments start with great coffee.\nWe serve freshly roasted beans, cozy vibes, and a friendly atmosphere that makes you feel at home.\nWhether you’re here to study, work, or just relax — Zar Café is your perfect spot.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 590, 150));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basicc.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -290, 1200, 1420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();

        new A__Welcome().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new C__About_us().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
private void styleButton(javax.swing.JButton btn) {
    // 1. تظبيط الشكل الأساسي
    btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    btn.setForeground(java.awt.Color.WHITE); // لون الكلام أبيض
    btn.setBackground(new java.awt.Color(102, 51, 0)); // لون الخلفية بني غامق (الأساسي)
    btn.setBorderPainted(false); // شيل البرواز عشان يبقى فلات (Flat)
    btn.setFocusPainted(false); // شيل المربع اللي بيظهر لما تدوس عليه
    btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // الماوس يقلب يد

    // 2. إضافة تفاعل الماوس (Hover Effect)
    btn.addMouseListener(new java.awt.event.MouseAdapter() {
        // لما الماوس يدخل على الزرار
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            // نفتح اللون شوية (لون بني أفتح)
            btn.setBackground(new java.awt.Color(165, 117, 68)); 
        }

        // لما الماوس يخرج من الزرار
        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            // نرجعه للون الأصلي الغامق
            btn.setBackground(new java.awt.Color(102, 51, 0)); 
        }
    });
}

// ده كلاس مسؤول عن رسم البرواز الدائري
class RoundedBorder implements javax.swing.border.Border {
    private int radius;
    private java.awt.Color color;

    RoundedBorder(int radius, java.awt.Color color) {
        this.radius = radius;
        this.color = color;
    }

    // 🔥 التعديل هنا: قللنا الهوامش عشان الكلام ميتكلش 🔥
    public java.awt.Insets getBorderInsets(java.awt.Component c) {
        // فوق وتحت: 5 بيكسل بس (عشان الكلام يبان)
        // يمين وشمال: نص القطر (15) عشان الكلام ميخبطش في الدوران
        return new java.awt.Insets(5, radius / 2, 5, radius / 2);
    }

    public boolean isBorderOpaque() { return true; }

    public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(color);
        g2.setStroke(new java.awt.BasicStroke(2));
        g2.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
    }
}
}

